name: Build wheels
on:
  push:
    branches:
      - main

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-24.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --tags
      - id: measurement-3
        name: Record Measurement After Fetch all tags
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Fetch all tags
          task: get-measurement
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build sdist (pep517)
        run: 'python -m pip install build

          python -m build --sdist

          '
      - id: measurement-6
        name: Record Measurement After Build sdist (pep517)
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build sdist (pep517)
          task: get-measurement
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist_files
          path: dist/*.tar.gz
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  build_wheels:
    name: Build ${{ matrix.only }}
    needs: generate-wheels-matrix
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --tags
      - id: measurement-3
        name: Record Measurement After Fetch all tags
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Fetch all tags
          task: get-measurement
      - if: runner.os == 'Linux'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
          only: ${{ matrix.only }}
      - uses: actions/upload-artifact@v4
        with:
          name: bdist_files_${{ matrix.only }}
          path: ./wheelhouse/*.whl
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-wheels-matrix.outputs.include) }}
  generate-wheels-matrix:
    name: Generate wheels matrix
    outputs:
      include: ${{ steps.set-matrix.outputs.include }}
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v4
      - name: Install cibuildwheel
        run: pipx install cibuildwheel==2.23.3
      - id: measurement-3
        name: Record Measurement After Install cibuildwheel
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install cibuildwheel
          task: get-measurement
      - name: Print all build identifiers
        run: cibuildwheel --print-build-identifiers
      - id: measurement-5
        name: Record Measurement After Print all build identifiers
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Print all build identifiers
          task: get-measurement
      - id: set-matrix
        run: "MATRIX=$(\n  {\n    cibuildwheel --print-build-identifiers --platform\
          \ linux \\\n    | jq -nRc '{\"only\": inputs, \"os\": \"ubuntu-latest\"\
          }' \\\n    && cibuildwheel --print-build-identifiers --platform macos \\\
          \n    | jq -nRc '{\"only\": inputs, \"os\": \"macos-latest\"}' \\\n    &&\
          \ cibuildwheel --print-build-identifiers --platform windows \\\n    | jq\
          \ -nRc '{\"only\": inputs, \"os\": \"windows-latest\"}'\n  } | jq -sc\n\
          )\necho \"include=$MATRIX\" >> $GITHUB_OUTPUT\n"
      - id: measurement-7
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  publish_pypi:
    environment:
      name: pypi
      url: https://pypi.org/p/shap
    if: startsWith(github.ref, 'refs/tags')
    name: Publish wheels to PyPI
    needs:
      - build_wheels
      - build_sdist
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
          pattern: bdist_files_*
      - uses: actions/download-artifact@v4
        with:
          name: sdist_files
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  publish_test_pypi:
    environment:
      name: testpypi
      url: https://test.pypi.org/p/shap
    name: Publish wheels to TestPyPI
    needs:
      - build_wheels
      - build_sdist
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
          pattern: bdist_files_*
      - uses: actions/download-artifact@v4
        with:
          name: sdist_files
          path: dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
